### ISSUE TITLE
Classes cannot be found

### ISSUE THREAD

**Issue by aana77** [davidmigloz/number-keyboard#14] opened 2018-06-19 08:38 UTC
I have imported your library with gradle. 
But it does not open in xml, says classes cannot be found.

**Comment by davidmigloz** [comment] 2018-06-19 09:35
Hi aana77,

Can you post the full error you are getting?

Thanks.

**Comment by aana77** [comment] 2018-06-19 09:40
![screenshot 2018-06-19 15 08 35](https://user-images.githubusercontent.com/13863269/41589683-c300fd68-73d2-11e8-8d68-807622ad0f5d.png)
Here is the screenshot of my implementation and the error that I am getting. 
I have already tried Clean&Build and Refresh on my layout.

**Comment by davidmigloz** [comment] 2018-06-19 11:27
Thanks for the info.

Have you correctly imported the library?
Can you show me your `build.gradle` file?

**Comment by aana77** [comment] 2018-06-19 12:53
![screenshot 2018-06-19 18 21 21](https://user-images.githubusercontent.com/13863269/41598432-c7cca8f4-73ed-11e8-9895-48f25ff6a8a1.png)
![screenshot 2018-06-19 18 21 29](https://user-images.githubusercontent.com/13863269/41598433-c80b1b20-73ed-11e8-8d1d-70aabcf97c45.png)
Here are the gradle files

**Comment by davidmigloz** [comment] 2018-06-20 22:07
Everything looks fine. I have not clue what can be the issue. Have you tried to restart Android Studio?

**Comment by aana77** [comment] 2018-06-21 06:58
Yes I have tried that too. 
This is strange, since I am able to use other classes, only this is creating an issue.

**Comment by davidmigloz** [comment] 2018-06-24 13:54
Is it an open source project? If so I can take a look to your code.

**Comment by Euniceadu** [comment] 2018-07-19 07:19
@aana77 changing the version from 2.0 to 2.0.1 fixed this issue for me

**Comment by davidmigloz** [comment] 2018-07-19 10:04
Yes, it was caused by this issue #9. Should be fixed now.

**Closed** 2018-07-19 10:06 UTC
Labels: bug
