### ISSUE TITLE
autoSizeTextType not found

### ISSUE THREAD

**Issue by johnny68** [davidmigloz/number-keyboard#12] opened 2018-04-27 14:03 UTC
Hi, great Library.
But it is giving me a headache.
`error: style attribute 'attr/autoSizeTextType (aka --package-name--:attr/autoSizeTextType)' not found. |  
-- | --`

This is the exact error it is giving me while I'm trying to compile it.
Remember i just added the dependency only.

If you need any more information I am happy to provide

**Comment by davidmigloz** [comment] 2018-04-27 22:24
Hi Johnny, thanks for using the library.
In version 2.0 I started using [Autosizing TextViews](https://developer.android.com/guide/topics/ui/look-and-feel/autosizing-textview). The error seems to be related with it. 
Are you using the support library, and if so, is it version 26.0.0 or above?
Can you show me your gradle file?

**Comment by davidmigloz** [comment] 2018-05-21 11:49
I'll close this issue as I couldn't reproduce with the information provided. Feel free to reopen it adding extra details.

**Closed by davidmigloz** 2018-05-21 11:49 UTC
